package com.gproject.recommend.mapper;

import com.gproject.recommend.pojo.Recommend;

public interface RecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer recomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated
     */
    int insert(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated
     */
    int insertSelective(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated
     */
    Recommend selectByPrimaryKey(Integer recomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Recommend record);
}