package com.gproject.recommend.pojo;

import java.util.Date;

public class Recommend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.recom_id
     *
     * @mbggenerated
     */
    private Integer recomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.category_id
     *
     * @mbggenerated
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.create_by
     *
     * @mbggenerated
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.last_updata_by
     *
     * @mbggenerated
     */
    private Integer lastUpdataBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.last_update_time
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.recom_id
     *
     * @return the value of recommend.recom_id
     *
     * @mbggenerated
     */
    public Integer getRecomId() {
        return recomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.recom_id
     *
     * @param recomId the value for recommend.recom_id
     *
     * @mbggenerated
     */
    public void setRecomId(Integer recomId) {
        this.recomId = recomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.user_id
     *
     * @return the value of recommend.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.user_id
     *
     * @param userId the value for recommend.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.product_id
     *
     * @return the value of recommend.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.product_id
     *
     * @param productId the value for recommend.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.category_id
     *
     * @return the value of recommend.category_id
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.category_id
     *
     * @param categoryId the value for recommend.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.create_time
     *
     * @return the value of recommend.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.create_time
     *
     * @param createTime the value for recommend.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.create_by
     *
     * @return the value of recommend.create_by
     *
     * @mbggenerated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.create_by
     *
     * @param createBy the value for recommend.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.last_updata_by
     *
     * @return the value of recommend.last_updata_by
     *
     * @mbggenerated
     */
    public Integer getLastUpdataBy() {
        return lastUpdataBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.last_updata_by
     *
     * @param lastUpdataBy the value for recommend.last_updata_by
     *
     * @mbggenerated
     */
    public void setLastUpdataBy(Integer lastUpdataBy) {
        this.lastUpdataBy = lastUpdataBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.last_update_time
     *
     * @return the value of recommend.last_update_time
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.last_update_time
     *
     * @param lastUpdateTime the value for recommend.last_update_time
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}